description: submitjob

target:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: msrmt
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: wu2
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

environment:
  registry: phillyregistry.azurecr.io
  image: philly/jobs/custom/pytorch:fairseq-0.6.2
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  data_upload: False
  local_dir: /home/v-jiaya/RetrieveNMT/data/JRC-Acquis/RetriveNMT/en-es/es2en/top2/data-bin/
  remote_dir: RetrieveNMT/data/JRC-Acquis/RetriveNMT/en-es/es2en/top2/data-bin/
#  storage_id: input


# list of jobs to run, we run 2 jobs in this example
jobs:
#- name: train_JRC-Acquis_en2de_only_select
#  sku: G4
#  command:
#    - bash ./shells/JRC-Acquis/selectlayer/train_JRC-Acquis_en2de.sh
- name: train_JRC-Acquis_en2de_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_en2de.sh
- name: train_JRC-Acquis_de2en_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_de2en.sh
- name: train_JRC-Acquis_en2fr_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_en2fr.sh
- name: train_JRC-Acquis_fr2en_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_fr2en.sh
- name: train_JRC-Acquis_en2es_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_en2es.sh
- name: train_JRC-Acquis_es2en_src-text
  sku: G4
  command:
    - bash ./shells/JRC-Acquis/src-text/train_JRC-Acquis_es2en.sh

#- name: train_JRC-Acquis_fr2en_segment
#  sku: G4
#  command:
#    - bash ./shells/JRC-Acquis/train_JRC-Acquis_fr2en.sh