description: submitjob

target:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: resrchvc
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: rr1
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

environment:
  registry: phillyregistry.azurecr.io
  image: philly/jobs/custom/pytorch:fairseq-0.6.2
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  data_upload: False
  local_dir: /home/v-jiaya/RetrieveNMT/data/MD/en-de/concat/data-bin/
  remote_dir: RetrieveNMT/data/MD/en-de/concat/data-bin/
#  storage_id: input
# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example
jobs:
- name: MD_train_en2de
  sku: G8
  command:
    - bash ./shells/MD/train_en2de.sh

